export interface StockingItem {
  /** Kód zdravotníckej pomôcky (G kód). */
  code: string;
  name: string;
  manufacturer: string | null;
  country: string | null;
  unit: string | null;
  /** Cena vrátane DPH v EUR. */
  price: number | null;
  /** Úhrada zdravotnej poisťovne v EUR. */
  covered: number | null;
  /** Doplatok pacienta v EUR. */
  copay: number | null;
  /** Preskripčné obmedzenia (odbornosti). */
  prescription: string[];
  note: string | null;
}

export interface StockingSubgroup {
  id: string;
  title: string;
  /** Limit spoluúčasti / úhrady v EUR. */
  limit: number | null;
  items: StockingItem[];
}

export interface StockingGroup {
  id: string;
  title: string;
  subgroups: StockingSubgroup[];
}

/** Skratky výrobcov podľa legendy zdrojového zoznamu. */
export const MANUFACTURERS: Record<string, string> = {
  "MAX": "Maxis",
  "ARA": "Avicenum",
  "LOA": "Loana",
  "LNN": "Lonaris",
  "DEO": "Deona",
  "TLP": "Thuasne",
  "CEZ": "Cizeta / CzSalus",
  "IBC": "Ibici",
  "TNE": "Tonus Elast (Litva)",
  "PTM": "Pani Teresa Medica",
  "BNJ": "BSN / Jobst",
  "MDB": "Medi Bayreuth",
  "GAN": "Ganzoni",
  "SAZ": "Salzmann",
  "LR": "Lohmann & Rauscher",
  "AHH": "Andover Healthcare",
};

export const STOCKING_GROUPS: StockingGroup[] = [
  {
    id: "G1",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY LÝTKOVÉ",
    subgroups: [
      {
        id: "G1.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 12.14,
        items: [
          {
            code: "G98243",
            name: "Pančuchy lýtkové Venoflex Micro® AD elastické, kompresívna trieda II., rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 12.04,
            covered: 12.04,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: "lem, telová/čierna, otv/uzavr., ťažšie sa navliekajú, sú tuhšie, lepšie pri veľkých opuchoch",
          },
          {
            code: "G88144",
            name: "VENOFLEX KOKOON AD elastické lýtkové pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: "s lemom!, telová/čierna, otvorená/uzavretá, ľahšie sa navliekajú",
          },
          {
            code: "G92212",
            name: "Venoflex FAST Coton AD elastické lýtkové pančuchy, II.kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 19.93,
            covered: 12.14,
            copay: 7.79,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: "lem, čierna, uzavr. ako ponožka, 46% bavlna, nedráždivá",
          },
          {
            code: "G88145",
            name: "VENOFLEX CITY CONFORT COTON AD elastické lýtkové pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 21.19,
            covered: 12.14,
            copay: 9.05,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: "lem, čierna, otv/uzavr., 46% bavlna, nedráždivá",
          },
          {
            code: "G1198A",
            name: "Pančuchy lýtkové Venoflex® Soft & Care AD elastické s viskózou, kompresívna trieda II., rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 22.11,
            covered: 12.14,
            copay: 9.97,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: "lem, čierna, uzavr., huňatá, nedráždivá, pre starších ľudí - nepotrebujú navliekač",
          },
          {
            code: "G00147",
            name: "Lýtkové pančuchy na mieru (uviesť 2ks)",
            manufacturer: null,
            country: null,
            unit: null,
            price: null,
            covered: null,
            copay: null,
            prescription: [],
            note: null,
          },
          {
            code: "G83622",
            name: "AVICENUM 360 COTTON s prímesou bavlny a mikrokapsulami Skintex",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 14.16,
            covered: 12.14,
            copay: 2.02,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G83623",
            name: "AVICENUM 360 COTTON Sanitized Silver",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 14.16,
            covered: 12.14,
            copay: 2.02,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G2143A",
            name: "Pančuchy lýtkové Avicenum PHLEBO 360 TRAVEL kompresná trieda II. (II. KT, CCL 2) uzavretá špička, veľkosť S normal- XXL long",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 11.75,
            covered: 11.75,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G5144A",
            name: "Pančuchy lýtkové Avicenum PHLEBO 360 TRAVEL COTTON zatvorená špica, veľkosti S normal - XXL long",
            manufacturer: "ARA",
            country: "CZ",
            unit: "ks",
            price: 12.1,
            covered: 12.1,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G79785",
            name: "AVICENUM 360 II. K.tr., skintex, microfibre, so špicou/bez špice",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 12.34,
            covered: 12.14,
            copay: 0.2,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G79786",
            name: "AVICENUM 360 II. K.tr., sanitized, microfibre, so špicou/bez špice",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 12.34,
            covered: 12.14,
            copay: 0.2,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G99345",
            name: "Pančuchy lýtkové Avicenum 360 FINE kompresívna trieda II, s/bez špice, short / normal / long, S-XXL",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 12.34,
            covered: 12.14,
            copay: 0.2,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G77661",
            name: "LONARIS Micro II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 10.78,
            covered: 10.78,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G58735",
            name: "Pančuchy Lonaris Exclusive lýtkové, farbené / 2ks, kompresná trieda 2",
            manufacturer: "LNN",
            country: "ČR",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G97636",
            name: "Pančuchy Lonaris Extra Feine Soft lýtkové, farbené / 2ks, kompresná trieda 2",
            manufacturer: "LNN",
            country: "ČR",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G97629",
            name: "Pančuchy Lonaris Micro Soft lýtkové, farbené / 2ks, kompresná trieda 2",
            manufacturer: "LNN",
            country: "ČR",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G98463",
            name: "Podkolienky kompresívne špeciálne AR1006 kompresná trieda 2, 140 den, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "pár",
            price: 12,
            covered: 12,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G70877",
            name: "Pančuchy kompresívné lýtkové DEONA SUPER, s/bez špice, kompres. tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 12.01,
            covered: 12.01,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G98469",
            name: "Podkolienky kompresívne pánske AR3103 kompresná trieda 2, z mikrovlákna, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "pár",
            price: 12.13,
            covered: 12.13,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G93116",
            name: "Podkolienky zdravotné kompresívne Kompresná trieda II. liečba varixov",
            manufacturer: "MOL",
            country: "IT",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G83679",
            name: "PROMAX Standard, lýtkové pančuchy",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G37411",
            name: "Segreta plus - high II. K.tr.",
            manufacturer: "IBC",
            country: "IT",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G81661",
            name: "Venosan 6002 II. K.tr.",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 12.14,
            covered: 12.14,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G70874",
            name: "DEONA KLASIK II. K.tr.",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 12.28,
            covered: 12.14,
            copay: 0.14,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G29732",
            name: "Lonaris Extra Fejne II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 12.29,
            covered: 12.14,
            copay: 0.15,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G67998",
            name: "LONARIS Cotton II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 13.7,
            covered: 12.14,
            copay: 1.56,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G74400",
            name: "MAXIS BRILLANT II. K. tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 13.52,
            covered: 12.14,
            copay: 1.38,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G27181",
            name: "Pančuchy lýtkové MAXIS COMFORT COTTON II. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 13.52,
            covered: 12.14,
            copay: 1.38,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G59875",
            name: "MAXIS-MICRO II. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 17.17,
            covered: 12.14,
            copay: 5.03,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G86384",
            name: "ELAST 0401 LUX - Pančuchy kompresívne lýtkové II. K.tr.",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 13.93,
            covered: 12.14,
            copay: 1.79,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G86388",
            name: "ELAST 0408 LUX - Pančuchy kompresívne lýtkové II. K.tr. Bez špice",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 13.93,
            covered: 12.14,
            copay: 1.79,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G83882",
            name: "Zdravotné sťahujúce podkolienky 2 trieda kompresie PT 0405 KT.2",
            manufacturer: "PTM",
            country: "PL",
            unit: "pár",
            price: 14.85,
            covered: 12.14,
            copay: 2.71,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G2845A",
            name: "Pančucha kompresívna lýtková JOBST OPAQUE telová / čierna farba, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 17.15,
            covered: 12.14,
            copay: 5.01,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G2833A",
            name: "Pančucha kompresívna lýtková pre mužov JOBST Explore čierna, veľkosť I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 18.14,
            covered: 12.14,
            copay: 6,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G2842A",
            name: "Pančucha kompresívna lýtková JOBST Ultra Sheer telová / čierna farba, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 18.64,
            covered: 12.14,
            copay: 6.5,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G79884",
            name: "MEDIVEN PLUS II. K.tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 20.54,
            covered: 12.14,
            copay: 8.4,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G79891",
            name: "MEDIVEN ACTIVE II. K.tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 21.56,
            covered: 12.14,
            copay: 9.42,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G79887",
            name: "MEDIVEN ELEGANCE II. K.tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 24.95,
            covered: 12.14,
            copay: 12.81,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G35089",
            name: "Sigvaris Plus II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 26.48,
            covered: 12.14,
            copay: 14.34,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
          {
            code: "G80893",
            name: "Venosan 5002 II. K.tr.",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 35.85,
            covered: 12.14,
            copay: 23.71,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER", "ORT"],
            note: null,
          },
        ],
      },
      {
        id: "G1.2.1",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 13.35,
        items: [
          {
            code: "G70875",
            name: "Pančuchy kompresívné lýtkové DEONA Klasik, s/bez špice, kompres tr. 3",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 13.2,
            covered: 13.2,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G86503",
            name: "Actico Silk kompresívna pančucha III. K.tr., dvojvrstvová",
            manufacturer: "LR",
            country: "DE",
            unit: "pár",
            price: 13.35,
            covered: 13.35,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G30920",
            name: "Lonaris Extra, k. tr. 3 III. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 13.35,
            covered: 13.35,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G93683",
            name: "AVICENUM 520 III.K.tr.pančuchy kompresívne lýtkové s/bez špičky",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 15.84,
            covered: 13.35,
            copay: 2.49,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G27182",
            name: "MAXIS-MICRO III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 16.14,
            covered: 13.35,
            copay: 2.79,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G35097",
            name: "Sigvaris Plus III. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 27.46,
            covered: 13.35,
            copay: 14.11,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G1.2.2",
        title: "KOMPRESNÁ TRIEDA III.stupeň set na liečbu vredu predkolenia",
        limit: 31.55,
        items: [
          {
            code: "G1941A",
            name: "Bandáž CoFlex TLC s kalamínom dvojkrokový nelatexovaný kompesný systém",
            manufacturer: "AHH",
            country: "US",
            unit: "ks",
            price: 17.82,
            covered: 17.82,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ZP"],
            note: null,
          },
          {
            code: "G1942A",
            name: "Bandáž CoFlex TLC so zinkom dvojkrokový nelatexovaný kompesný systém",
            manufacturer: "AHH",
            country: "US",
            unit: "set",
            price: 18.15,
            covered: 18.15,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ZP"],
            note: null,
          },
          {
            code: "G1199A",
            name: "Kit Biflex, súprava kompresívnych obväzov s kalibráciou dva druhy obväzov na báze viskózy bez latexu, 3 veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "set",
            price: 30.95,
            covered: 30.95,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ZP"],
            note: null,
          },
          {
            code: "G83678",
            name: "Mediven ulcer kit",
            manufacturer: "MDB",
            country: "DE",
            unit: "set",
            price: 31.55,
            covered: 31.55,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ZP"],
            note: null,
          },
        ],
      },
      {
        id: "G1.3",
        title: "KOMPRESNÁ TRIEDA IV. stupeň",
        limit: 33.13,
        items: [
          {
            code: "G35100",
            name: "Sigvaris Plus IV. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 33.13,
            covered: 33.13,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G2",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY POLOSTEHENNÉ",
    subgroups: [
      {
        id: "G2.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 15.91,
        items: [
          {
            code: "G77662",
            name: "LONARIS Micro II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 14.18,
            covered: 14.18,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G29733",
            name: "Lonaris Extra Fejne II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 15.91,
            covered: 15.91,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G67999",
            name: "LONARIS Cotton II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 17.09,
            covered: 15.91,
            copay: 1.18,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G59876",
            name: "MAXIS MICRO II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 17.94,
            covered: 15.91,
            copay: 2.03,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G59877",
            name: "MAXIS MICRO II. K.tr., nekĺzavá úprava",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 18.7,
            covered: 15.91,
            copay: 2.79,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
        ],
      },
      {
        id: "G2.2",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 17.44,
        items: [
          {
            code: "G27223",
            name: "MAXIS-MICRO III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 20.37,
            covered: 17.44,
            copay: 2.93,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G3",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY STEHENNÉ",
    subgroups: [
      {
        id: "G3.1.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 16.91,
        items: [
          {
            code: "G88146",
            name: "VENOFLEX KOKOON AG elastické stehenné pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 22.57,
            covered: 16.91,
            copay: 5.66,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: "s krajkou!, telová/čierna, otvorená/uzavretá, ľahšie sa navliekajú",
          },
          {
            code: "G98244",
            name: "Pančuchy stehenné Venoflex Micro® AG elastické s nekĺzavým ukončením, kompresívna trieda II.",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 16.9,
            covered: 16.9,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: "čipka/lem, telová/čierna, otv/uzavr., ťažšie sa navliekajú, sú tuhšie, lepšie pri veľkých opuchoch",
          },
          {
            code: "G88147",
            name: "VENOFLEX CITY CONFORT COTON AG elastické stehenné pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 34.53,
            covered: 16.91,
            copay: 17.62,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: "iba lem, iba čierna, otv/uzavr., 42% podiel bavlny - menej dráždivé na pokožku), oficiálne sú pánske - majú dlhšie chodidlo",
          },
          {
            code: "G00149",
            name: "Stehenné pančuchy na mieru (uviesť 2ks)",
            manufacturer: null,
            country: null,
            unit: null,
            price: null,
            covered: null,
            copay: null,
            prescription: [],
            note: null,
          },
          {
            code: "G79787",
            name: "AVICENUM 360 II. K.tr.",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 19.21,
            covered: 16.91,
            copay: 2.3,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G93117",
            name: "Pančuchy zdravotné kompresívne stehenné Kompresná trieda II. liečba varixov",
            manufacturer: "MOL",
            country: "IT",
            unit: "pár",
            price: 16.91,
            covered: 16.91,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G83681",
            name: "PROMAX Standard, stehenné panč.nekĺz. úprava",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 16.91,
            covered: 16.91,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G37410",
            name: "Segreta plus stocking II. K.tr.",
            manufacturer: "IBC",
            country: "IT",
            unit: "pár",
            price: 16.91,
            covered: 16.91,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G81901",
            name: "Venosan 6002 II. K.tr.",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 16.91,
            covered: 16.91,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G86385",
            name: "ELAST 0402 LUX - Pančuchy kompresívne stehenné II. K.tr. nekĺzavá úprava",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 19.73,
            covered: 16.91,
            copay: 2.82,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G86386",
            name: "ELAST 0403 LUX - Pančuchy kompresívne stehenné II. K.tr. bez špice,nekĺzavá úprava",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 19.73,
            covered: 16.91,
            copay: 2.82,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G88887",
            name: "Zdravotné sťahujúce pančuchy 2 trieda kompresie PT 0403 KT.2, liečba varixov",
            manufacturer: "PTM",
            country: "PL",
            unit: "pár",
            price: 19.8,
            covered: 16.91,
            copay: 2.89,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G2846A",
            name: "Pančucha kompresívna stehenná JOBST OPAQUE telová / čierna farba, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 20.7,
            covered: 16.91,
            copay: 3.79,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G2843A",
            name: "Pančucha kompresívna stehenná JOBST Ultra Sheer telová / čierna farba, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 25.59,
            covered: 16.91,
            copay: 8.68,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G79888",
            name: "MEDIVEN ELEGANCE II. K.tr., s nekĺzavou úpravou",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 37.73,
            covered: 16.91,
            copay: 20.82,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G79885",
            name: "MEDIVEN PLUS II. K.tr., s nekĺzavou úpravou",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 37.73,
            covered: 16.91,
            copay: 20.82,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G81899",
            name: "Venosan 5002 II. K.tr.",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 51.99,
            covered: 16.91,
            copay: 35.08,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G35091",
            name: "Sigvaris Plus II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 53.29,
            covered: 16.91,
            copay: 36.38,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G79788",
            name: "AVICENUM 360 II. K.tr.",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 19.21,
            covered: 16.91,
            copay: 2.3,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G96301",
            name: "Avicenum 360 FINE stehenné pančuchy KRAJKA/LEM, s/bez špice",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 19.21,
            covered: 16.91,
            copay: 2.3,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G83624",
            name: "AVICENUM 360 COTTON stehenné pančuchy s prímesou bavlny a mikrokapsulami Skintex",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 21.81,
            covered: 16.91,
            copay: 4.9,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G83625",
            name: "AVICENUM 360 COTTON stehenné pančuchy s prímesou bavlny a úpravou Sanitized Silver",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 21.81,
            covered: 16.91,
            copay: 4.9,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G70870",
            name: "Pančuchy kompresívné stehenné DEONA Klasik, samodrž. lem, s/bez špice, kompres. tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 16.76,
            covered: 16.76,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G70876",
            name: "Pančuchy kompresívné stehenné DEONA SUPER, samodrž. krajka, s/bez špice, kompres. tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 16.76,
            covered: 16.76,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G59879",
            name: "MAXIS-MICRO II. K.tr., nekĺzavá úprava",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 28.63,
            covered: 16.91,
            copay: 11.72,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G59878",
            name: "MAXIS MICRO II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 19.09,
            covered: 16.91,
            copay: 2.18,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G74401",
            name: "MAXIS BRILLANT II. K. tr., s nekĺzavou úpravou",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 19.84,
            covered: 16.91,
            copay: 2.93,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G52805",
            name: "Pančuchy stehenné MAXIS-COMFORT COTTON II. K.tr., nekĺzavá úprava",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 19.84,
            covered: 16.91,
            copay: 2.93,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G77663",
            name: "LONARIS Micro II. K.tr., samodržiaci lem",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 15.85,
            covered: 15.85,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G29734",
            name: "Lonaris Extra Fejne II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 17.11,
            covered: 16.91,
            copay: 0.2,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G68000",
            name: "LONARIS COTTON II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 18.45,
            covered: 16.91,
            copay: 1.54,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G58739",
            name: "Pančuchy Lonaris Extra Feine Soft stehenné,farebné,nekĺzavá úprava,kompresná trieda 2",
            manufacturer: "LNN",
            country: "ČR",
            unit: "pár",
            price: 19.21,
            covered: 16.91,
            copay: 2.3,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G58738",
            name: "Pančuchy Lonaris Micro Soft stehenné,farebné,nekĺzavá úprava,kompresná trieda 2",
            manufacturer: "LNN",
            country: "ČR",
            unit: "pár",
            price: 19.21,
            covered: 16.91,
            copay: 2.3,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G58737",
            name: "Pančuchy Lonaris Exclusive stehenné,farebné,nekĺzavá úprava,kompresná trieda 2",
            manufacturer: "LNN",
            country: "ČR",
            unit: "pár",
            price: 19.21,
            covered: 16.91,
            copay: 2.3,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G68001",
            name: "LONARIS COTTON II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 19.84,
            covered: 16.91,
            copay: 2.93,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G36824",
            name: "Lonaris II. K.tr., s čipkou",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 19.84,
            covered: 16.91,
            copay: 2.93,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G36823",
            name: "Lonaris Extra II. K.tr., nekĺzavá úprava",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 19.84,
            covered: 16.91,
            copay: 2.93,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
        ],
      },
      {
        id: "G3.1.2",
        title: "KOMPRESNÁ TRIEDA II.stupeň špeciálne",
        limit: 18.99,
        items: [
          {
            code: "G99346",
            name: "Pančuchy stehenné Avicenum Hospital 2 kompresívna trieda II, S-XXL",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 11.48,
            covered: 11.48,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G98464",
            name: "Pančuchy kompresné stehenné špeciálne AR 1007 kompresná trieda 2, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "pár",
            price: 18,
            covered: 18,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G93115",
            name: "Pančuchy stehenné Kompresná trieda II. liečba varixov, špeciálna",
            manufacturer: "MOL",
            country: "IT",
            unit: "pár",
            price: 18.99,
            covered: 18.99,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G94282",
            name: "Pančuchy stehenné VENOFLEX® Clinic elastické špeciálne, rôzne veľkosti, kompr.trieda II",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 18.99,
            covered: 18.99,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G83881",
            name: "Pančucha stehenná PT 0404 II. K.tr.špeciálna",
            manufacturer: "PTM",
            country: "PL",
            unit: "pár",
            price: 19.54,
            covered: 18.99,
            copay: 0.55,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
        ],
      },
      {
        id: "G3.2",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 19.1,
        items: [
          {
            code: "G30922",
            name: "Lonaris Extra III. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 19.1,
            covered: 19.1,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G93684",
            name: "AVICENUM 520 III.K.tr.pančuchy kompresívne stehenné s/bez špičky",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 22.32,
            covered: 19.1,
            copay: 3.22,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G27224",
            name: "MAXIS-MICRO III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 22.32,
            covered: 19.1,
            copay: 3.22,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G35099",
            name: "Sigvaris Plus III. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 53.78,
            covered: 19.1,
            copay: 34.68,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G3.3",
        title: "KOMPRESNÁ TRIEDA IV. stupeň",
        limit: 52.07,
        items: [
          {
            code: "G35102",
            name: "Sigvaris Plus IV. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 52.07,
            covered: 52.07,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G4",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY STEHENNÉ S UCHYTENÍM V PÁSE",
    subgroups: [
      {
        id: "G4.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 10.51,
        items: [
          {
            code: "G77664",
            name: "LONARIS Micro, stehenná pančucha II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 9.42,
            covered: 9.42,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G29735",
            name: "Lonaris Extra II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 10.51,
            covered: 10.51,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G93682",
            name: "AVICENUM 360 II.K.tr.pančucha kompresívna stehenná s/bez špičky, s upínaním v páse",
            manufacturer: "ARA",
            country: "CZ",
            unit: "ks",
            price: 12.12,
            covered: 10.51,
            copay: 1.61,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G59880",
            name: "MAXIS MICRO II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 12.43,
            covered: 10.51,
            copay: 1.92,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G72323",
            name: "VENO ELEGANCE AG/HT II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 22.99,
            covered: 10.51,
            copay: 12.48,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G35105",
            name: "SIGVARIS - stehenná pančucha II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 27.21,
            covered: 10.51,
            copay: 16.7,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
        ],
      },
      {
        id: "G4.2",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 11.52,
        items: [
          {
            code: "G27225",
            name: "MAXIS-MICRO III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "ks",
            price: 13.38,
            covered: 11.52,
            copay: 1.86,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G5",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHOVÉ NOHAVICE",
    subgroups: [
      {
        id: "G5.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň, dámske",
        limit: 32.27,
        items: [
          {
            code: "G98465",
            name: "Nohavice pančuchové kompresné dámske AR 0008 kompresná trieda 2, 140 den, rôzne veľkosti a farby",
            manufacturer: "CZN",
            country: "IT",
            unit: "ks",
            price: 31.5,
            covered: 31.5,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G98466",
            name: "Nohavice pančuchové kompresívne špeciálne AR1009 kompresná trieda 2,140 den, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "ks",
            price: 32,
            covered: 32,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G5143A",
            name: "Nohavice pančuchové Avicenum PHLEBO 360 FINE otvorená špica / zatvorená špica, veľkosti S normal - XXL long",
            manufacturer: "ARA",
            country: "CZ",
            unit: "ks",
            price: 32.21,
            covered: 32.21,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G98467",
            name: "Nohavice pančuchové kompresné dámske AR 0010 kompresná trieda 2, so zatvorenou špicou, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "ks",
            price: 32.26,
            covered: 32.26,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G98245",
            name: "Pančuchové nohavice Venoflex Micro® AT elastické, kompresívna trieda II., rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 32.26,
            covered: 32.26,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G77665",
            name: "LONARIS Micro II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 32.27,
            covered: 32.27,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G93114",
            name: "Nohavice pančuchové zdravotné Kompresná trieda II. liečba varixov S, M, L, XL, XXL",
            manufacturer: "MOL",
            country: "IT",
            unit: "ks",
            price: 32.27,
            covered: 32.27,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G92211",
            name: "Venoflex Kokoon AT elastické pančuchové nohavice, II.kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 32.27,
            covered: 32.27,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G81902",
            name: "Venosan 6002 II. K.tr.",
            manufacturer: "SAZ",
            country: "CH",
            unit: "ks",
            price: 32.27,
            covered: 32.27,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G86506",
            name: "Avicenum 360 Nohavice pančuchové dámske II.KT",
            manufacturer: "ARS",
            country: "CZ",
            unit: "ks",
            price: 33.12,
            covered: 32.27,
            copay: 0.85,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G83880",
            name: "Zdravotné sťahujúce pančuchové nohavice 2 trieda kompresie PT 0401 KT.2, liečba varixov",
            manufacturer: "PTM",
            country: "PL",
            unit: "ks",
            price: 33.26,
            covered: 32.27,
            copay: 0.99,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G59881",
            name: "MAXIS-MICRO II. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "ks",
            price: 35.22,
            covered: 32.27,
            copay: 2.95,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G86387",
            name: "ELAST 0404 LUX - Nohavice pančuchové kompresívne II. K.tr.",
            manufacturer: "TNE",
            country: "LV",
            unit: "ks",
            price: 36.14,
            covered: 32.27,
            copay: 3.87,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G36817",
            name: "Lonaris Extra II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 36.14,
            covered: 32.27,
            copay: 3.87,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G74402",
            name: "MAXIS BRILLANT II. K. tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 36.14,
            covered: 32.27,
            copay: 3.87,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G37409",
            name: "Segreta plus panthyhose II. K.tr.",
            manufacturer: "IBC",
            country: "IT",
            unit: "ks",
            price: 36.14,
            covered: 32.27,
            copay: 3.87,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G72327",
            name: "VENO MICRO AT II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 36.14,
            covered: 32.27,
            copay: 3.87,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G2847A",
            name: "Pančuchové nohavice kompresívne JOBST OPAQUE telová / čierna farba, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 36.27,
            covered: 32.27,
            copay: 4,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G2844A",
            name: "Pančuchové nohavice kompresívne JOBST Ultra Sheer telová / čierna farba, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 38.77,
            covered: 32.27,
            copay: 6.5,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G79886",
            name: "MEDIVEN PLUS II. K.tr., dámske",
            manufacturer: "MDB",
            country: "DE",
            unit: "ks",
            price: 40.46,
            covered: 32.27,
            copay: 8.19,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G79889",
            name: "MEDIVEN ELEGANCE II. K.tr., dámske",
            manufacturer: "MDB",
            country: "DE",
            unit: "ks",
            price: 41.41,
            covered: 32.27,
            copay: 9.14,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G72325",
            name: "VENO ELEGANCE AT",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 43.9,
            covered: 32.27,
            copay: 11.63,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G35092",
            name: "Sigvaris Plus II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "ks",
            price: 56.51,
            covered: 32.27,
            copay: 24.24,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
        ],
      },
      {
        id: "G5.2",
        title: "KOMPRESNÁ TRIEDA II. stupeň, tehotenské",
        limit: 47.82,
        items: [
          {
            code: "G74403",
            name: "MAXIS BRILLANT II. K. tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 45.03,
            covered: 45.03,
            copay: 0,
            prescription: ["ANG", "CCH", "INT", "GYN"],
            note: null,
          },
          {
            code: "G59882",
            name: "Maxis-Micro II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 45.03,
            covered: 45.03,
            copay: 0,
            prescription: ["ANG", "CCH", "INT", "GYN"],
            note: null,
          },
          {
            code: "G77667",
            name: "LONARIS Micro II. K. tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 47.82,
            covered: 47.82,
            copay: 0,
            prescription: ["ANG", "CCH", "INT", "GYN"],
            note: null,
          },
          {
            code: "G36819",
            name: "Lonaris Extra II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 53.43,
            covered: 47.82,
            copay: 5.61,
            prescription: ["ANG", "CCH", "INT", "GYN"],
            note: null,
          },
          {
            code: "G72328",
            name: "VENO ELEGANCE AT/U II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 53.43,
            covered: 47.82,
            copay: 5.61,
            prescription: ["ANG", "CCH", "INT", "GYN"],
            note: null,
          },
          {
            code: "G79890",
            name: "MEDIVEN ELEGANCE II. K. tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "ks",
            price: 53.46,
            covered: 47.82,
            copay: 5.64,
            prescription: ["ANG", "CCH", "INT", "GYN"],
            note: null,
          },
          {
            code: "G35093",
            name: "Sigvaris Plus II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "ks",
            price: 64.92,
            covered: 47.82,
            copay: 17.1,
            prescription: ["ANG", "CCH", "INT", "GYN"],
            note: null,
          },
        ],
      },
      {
        id: "G5.3",
        title: "KOMPRESNÁ TRIEDA II. stupeň, pánske",
        limit: 50.98,
        items: [
          {
            code: "G59883",
            name: "Maxis-Micro II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 45.03,
            covered: 45.03,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G77666",
            name: "LONARIS Micro II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 50.98,
            covered: 50.98,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G36818",
            name: "Lonaris Extra II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 56.98,
            covered: 50.98,
            copay: 6,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
          {
            code: "G72330",
            name: "VENO ELEGANCE AT/H II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 56.98,
            covered: 50.98,
            copay: 6,
            prescription: ["ANG", "CCH", "CHI", "INT", "DER"],
            note: null,
          },
        ],
      },
    ],
  },
];
