/**
 * Zoznam kategorizovaných pomôcok na kompresívnu liečbu (celá kapitola G).
 *
 * Zdroj: Ministerstvo zdravotníctva SR, Zoznam kategorizovaných zdravotníckych
 * pomôcok, časť 1 (Zoznam_ZP_202607.xlsx). Údaje sú generované priamo z tohto
 * súboru - pri novej kategorizácii stačí stiahnuť nový zoznam a súbor
 * pregenerovať, nič sa neprepisuje ručne.
 */

/** Obdobie platnosti kategorizácie, z ktorej sú údaje prevzaté. */
export const CATEGORISATION = {
  id: "202607",
  validFrom: "2026-07-01",
  validTo: "2026-09-30",
  label: "1. 7. 2026 - 30. 9. 2026",
  sourceUrl: "https://www.health.gov.sk/Clanok?zkzp-202607",
} as const;

export interface StockingItem {
  /** Kód zdravotníckej pomôcky (G kód). */
  code: string;
  name: string;
  /** Doplnok názvu podľa kategorizácie. */
  detail: string | null;
  manufacturer: string | null;
  country: string | null;
  unit: string | null;
  /** Úradne určená cena (AKC) v EUR. */
  price: number | null;
  /** Úhrada zdravotnej poisťovne (ÚZP) v EUR. */
  covered: number | null;
  /** Doplatok pacienta (DOP) v EUR. */
  copay: number | null;
  /** Preskripčné obmedzenia (odbornosti). */
  prescription: string[];
  /** Praktická poznámka k pomôcke (nie je súčasťou kategorizácie). */
  note: string | null;
}

export interface StockingSubgroup {
  id: string;
  title: string;
  /** Najvyššia úhrada zdravotnej poisťovne v rámci podskupiny, v EUR. */
  limit: number | null;
  items: StockingItem[];
}

export interface StockingGroup {
  id: string;
  title: string;
  subgroups: StockingSubgroup[];
}

/** Skratky výrobcov podľa legendy zdrojového zoznamu. */
export const MANUFACTURERS: Record<string, string> = {
  "MAX": "Maxis",
  "ARA": "Avicenum",
  "LOA": "Loana",
  "LNN": "Lonaris",
  "DEO": "Deona",
  "TLP": "Thuasne",
  "THU": "Thuasne",
  "CEZ": "Cizeta / CzSalus",
  "IBC": "Ibici",
  "TNE": "Tonus Elast (Litva)",
  "PTM": "Pani Teresa Medica",
  "BNJ": "BSN / Jobst",
  "MDB": "Medi Bayreuth",
  "GAN": "Ganzoni",
  "SAZ": "Salzmann",
  "LR": "Lohmann & Rauscher",
  "AHH": "Andover Healthcare",
};

export const STOCKING_GROUPS: StockingGroup[] = [
  {
    id: "G1",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY LÝTKOVÉ",
    subgroups: [
      {
        id: "G1.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 11.6,
        items: [
          {
            code: "G77661",
            name: "LONARIS Micro",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 10.29,
            covered: 10.29,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G2143A",
            name: "Pančuchy lýtkové Avicenum PHLEBO 360 TRAVEL",
            detail: "kompresná trieda II. (II. KT, CCL 2) uzavretá špička, veľkosť S normal- XXL long",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 11.21,
            covered: 11.21,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G98463",
            name: "Podkolienky kompresívne špeciálne AR1006",
            detail: "kompresná trieda 2, 140 den, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "pár",
            price: 11.45,
            covered: 11.45,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G70877",
            name: "Pančuchy kompresívné lýtkové DEONA",
            detail: "SUPER, s/bez špice, kompres. tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 11.47,
            covered: 11.47,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G6104A",
            name: "Podkolienky zdravotné kompresívne",
            detail: "kompresná trieda II.",
            manufacturer: "MZX",
            country: "TR",
            unit: "pár",
            price: 11.55,
            covered: 11.55,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G98469",
            name: "Podkolienky kompresívne pánske AR3103",
            detail: "kompresná trieda 2, z mikrovlákna, rôzne veľkosti  a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "pár",
            price: 11.58,
            covered: 11.58,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G58735",
            name: "Pančuchy Lonaris Exclusive",
            detail: "lýtkové, farbené / 2ks, kompresná trieda 2",
            manufacturer: "LNN",
            country: "CZ",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G97636",
            name: "Pančuchy Lonaris Extra Feine Soft",
            detail: "lýtkové, farbené / 2ks, kompresná trieda 2",
            manufacturer: "LNN",
            country: "CZ",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G97629",
            name: "Pančuchy Lonaris Micro Soft",
            detail: "lýtkové, farbené / 2ks, kompresná trieda 2",
            manufacturer: "LNN",
            country: "CZ",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G81661",
            name: "Pančuchy lýtkové Venosan 6002",
            detail: "S-XL, kompres. trieda 2",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G93116",
            name: "Podkolienky zdravotné kompresívne",
            detail: "Kompresná trieda II. liečba varixov",
            manufacturer: "MOL",
            country: "IT",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G83679",
            name: "PROMAX Standard, lýtkové pančuchy",
            detail: null,
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G37411",
            name: "Segreta plus - high",
            detail: "II. K.tr.",
            manufacturer: "IBC",
            country: "IT",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G72320",
            name: "VENO MICRO AD",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G88144",
            name: "VENOFLEX KOKOON AD",
            detail: "elastické lýtkové pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 11.59,
            covered: 11.59,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: "s lemom!, telová/čierna, otvorená/uzavretá, ľahšie sa navliekajú",
          },
          {
            code: "G70874",
            name: "DEONA KLASIK",
            detail: "II. K.tr.",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 11.72,
            covered: 11.6,
            copay: 0.12,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G29732",
            name: "Lonaris Extra Fejne",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 11.73,
            covered: 11.6,
            copay: 0.13,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G79785",
            name: "AVICENUM 360",
            detail: "II. K.tr., skintex, microfibre, so špicou/bez špice",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 11.78,
            covered: 11.6,
            copay: 0.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G27181",
            name: "Pančuchy lýtkové MAXIS COMFORT COTTON",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 12.9,
            covered: 11.6,
            copay: 1.3,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G67998",
            name: "LONARIS Cotton",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 13.08,
            covered: 11.6,
            copay: 1.48,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G86384",
            name: "ELAST 0401 LUX - Pančuchy kompresívne lýtkové",
            detail: "II. K.tr.",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 13.29,
            covered: 11.6,
            copay: 1.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G86388",
            name: "ELAST 0408 LUX - Pančuchy kompresívne lýtkové",
            detail: "II. K.tr. Bez špice",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 13.29,
            covered: 11.6,
            copay: 1.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G79786",
            name: "AVICENUM 360",
            detail: "II. K.tr., sanitized, microfibre, so špicou/bez špice",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 13.39,
            covered: 11.6,
            copay: 1.79,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G83622",
            name: "AVICENUM 360 COTTON",
            detail: "s prímesou bavlny a mikrokapsulami Skintex",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 13.52,
            covered: 11.6,
            copay: 1.92,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G83623",
            name: "AVICENUM 360 COTTON",
            detail: "Sanitized Silver",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 13.52,
            covered: 11.6,
            copay: 1.92,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G99345",
            name: "Pančuchy lýtkové Avicenum 360 FINE",
            detail: "kompresívna trieda II, s/bez špice, short / normal / long, S-XXL",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 13.9,
            covered: 11.6,
            copay: 2.3,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G83882",
            name: "Zdravotné sťahujúce podkolienky 2 trieda  kompresie PT 0405",
            detail: "KT.2",
            manufacturer: "PTM",
            country: "PL",
            unit: "pár",
            price: 14.18,
            covered: 11.6,
            copay: 2.58,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G5144A",
            name: "Pančuchy lýtkové Avicenum PHLEBO 360 TRAVEL COTTON",
            detail: "zatvorená špica, veľkosti S normal - XXL long",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 16.05,
            covered: 11.6,
            copay: 4.45,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G98243",
            name: "Pančuchy lýtkové Venoflex Micro® AD",
            detail: "elastické, kompresívna trieda II., rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 16.25,
            covered: 11.6,
            copay: 4.65,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: "lem, telová/čierna, otv/uzavr., ťažšie sa navliekajú, sú tuhšie, lepšie pri veľkých opuchoch",
          },
          {
            code: "G2845A",
            name: "Pančucha kompresívna lýtková JOBST OPAQUE CCL2",
            detail: "2. kompresná trieda (KT II.), rôzne farby, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "pár",
            price: 16.37,
            covered: 11.6,
            copay: 4.77,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G74400",
            name: "MAXIS BRILLANT",
            detail: "II. K. tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 16.39,
            covered: 11.6,
            copay: 4.79,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G59875",
            name: "MAXIS-MICRO",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 16.39,
            covered: 11.6,
            copay: 4.79,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G2833A",
            name: "Pančucha kompresívna lýtková pre mužov JOBST Explore CCL2",
            detail: "2. kompresná trieda (KT II.)., čierna, veľkosť I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "pár",
            price: 17.31,
            covered: 11.6,
            copay: 5.71,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G2842A",
            name: "Pančucha kompresívna lýtková JOBST Ultra Sheer CCL2",
            detail: "2. kompresná trieda (KT II.), rôzne farby, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "pár",
            price: 17.79,
            covered: 11.6,
            copay: 6.19,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G92212",
            name: "Venoflex FAST Coton AD",
            detail: "elastické lýtkové pančuchy, II.kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 19.03,
            covered: 11.6,
            copay: 7.43,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: "lem, čierna, uzavr. ako ponožka, 46% bavlna, nedráždivá",
          },
          {
            code: "G79884",
            name: "MEDIVEN PLUS",
            detail: "II. K.tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 19.61,
            covered: 11.6,
            copay: 8.01,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G72319",
            name: "VENO ELEGANCE AD",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 20.03,
            covered: 11.6,
            copay: 8.43,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G88145",
            name: "VENOFLEX CITY CONFORT COTON AD",
            detail: "elastické lýtkové pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 20.22,
            covered: 11.6,
            copay: 8.62,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: "lem, čierna, otv/uzavr., 46% bavlna, nedráždivá",
          },
          {
            code: "G79891",
            name: "MEDIVEN ACTIVE",
            detail: "II. K.tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 20.58,
            covered: 11.6,
            copay: 8.98,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G1198A",
            name: "Pančuchy lýtkové Venoflex® Soft & Care AD",
            detail: "elastické s viskózou, kompresívna trieda II., rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 21.11,
            covered: 11.6,
            copay: 9.51,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: "lem, čierna, uzavr., huňatá, nedráždivá, pre starších ľudí - nepotrebujú navliekač",
          },
          {
            code: "G7634A",
            name: "Pančuchy kompresívne lýtkové Venoflex Men AD",
            detail: "s vysokým podielom bavlny, II. kompresívna trieda",
            manufacturer: "THU",
            country: "DE",
            unit: "pár",
            price: 21.55,
            covered: 11.6,
            copay: 9.95,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G79887",
            name: "MEDIVEN ELEGANCE",
            detail: "II. K.tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 23.81,
            covered: 11.6,
            copay: 12.21,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G35089",
            name: "Sigvaris Plus",
            detail: "II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 25.28,
            covered: 11.6,
            copay: 13.68,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
          {
            code: "G80893",
            name: "Pančuchy lýtkové Venosan 5002",
            detail: "klasický patent, S-XL, kompres. trieda 2",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 34.22,
            covered: 11.6,
            copay: 22.62,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT", "ORT"],
            note: null,
          },
        ],
      },
      {
        id: "G1.2.1",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 12.75,
        items: [
          {
            code: "G70875",
            name: "Pančuchy kompresívné lýtkové DEONA",
            detail: "Klasik, s/bez špice, kompres tr. 3",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 12.6,
            covered: 12.6,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G86503",
            name: "Actico  Silk  kompresívna pančucha",
            detail: "III. K.tr., dvojvrstvová",
            manufacturer: "LR",
            country: "DE",
            unit: "pár",
            price: 12.74,
            covered: 12.74,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G30920",
            name: "Lonaris Extra, k. tr. 3",
            detail: "III. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 12.74,
            covered: 12.74,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G93683",
            name: "AVICENUM 520",
            detail: "III.K.tr.pančuchy kompresívne lýtkové s/bez špičky",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 15.12,
            covered: 12.75,
            copay: 2.37,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G27182",
            name: "MAXIS-MICRO",
            detail: "III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 15.41,
            covered: 12.75,
            copay: 2.66,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G35097",
            name: "Sigvaris Plus",
            detail: "III. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 26.21,
            covered: 12.75,
            copay: 13.46,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G1.2.2",
        title: "KOMPRESNÁ TRIEDA III.stupeň",
        limit: 30.11,
        items: [
          {
            code: "G1199A",
            name: "Kit Biflex, súprava kompresívnych obväzov s kalibráciou",
            detail: "dva druhy obväzov na báze viskózy bez latexu, 3 veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "set",
            price: 29.55,
            covered: 29.55,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ZP"],
            note: null,
          },
          {
            code: "G83678",
            name: "Mediven ulcer kit",
            detail: null,
            manufacturer: "MDB",
            country: "DE",
            unit: "set",
            price: 30.11,
            covered: 30.11,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ZP"],
            note: null,
          },
        ],
      },
      {
        id: "G1.3",
        title: "KOMPRESNÁ TRIEDA IV. stupeň",
        limit: 31.63,
        items: [
          {
            code: "G35100",
            name: "Sigvaris Plus",
            detail: "IV. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 31.63,
            covered: 31.63,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G2",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY POLOSTEHENNÉ",
    subgroups: [
      {
        id: "G2.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 15.19,
        items: [
          {
            code: "G77662",
            name: "LONARIS Micro",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 13.53,
            covered: 13.53,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G29733",
            name: "Lonaris Extra Fejne",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 15.18,
            covered: 15.18,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G67999",
            name: "LONARIS Cotton",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 16.32,
            covered: 15.19,
            copay: 1.13,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G59876",
            name: "MAXIS MICRO",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 17.12,
            covered: 15.19,
            copay: 1.93,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G59877",
            name: "MAXIS MICRO",
            detail: "II. K.tr., nekĺzavá úprava",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 17.85,
            covered: 15.19,
            copay: 2.66,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G2.2",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 16.65,
        items: [
          {
            code: "G27223",
            name: "MAXIS-MICRO",
            detail: "III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 19.44,
            covered: 16.65,
            copay: 2.79,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G3",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY STEHENNÉ",
    subgroups: [
      {
        id: "G3.1.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 16.15,
        items: [
          {
            code: "G77663",
            name: "LONARIS Micro",
            detail: "II. K.tr., samodržiaci lem",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 15.13,
            covered: 15.13,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G70876",
            name: "Pančuchy kompresívné stehenné DEONA",
            detail: "SUPER, samodrž. krajka, s/bez špice, kompres. tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 16,
            covered: 16,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G70870",
            name: "Pančuchy kompresívné stehenné DEONA",
            detail: "Klasik, samodrž. lem, s/bez špice, kompres. tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "pár",
            price: 16,
            covered: 16,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G6063A",
            name: "Pančuchy stehenné kompresívne",
            detail: "kompresná trieda II.",
            manufacturer: "MZX",
            country: "TR",
            unit: "pár",
            price: 16.13,
            covered: 16.13,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G81901",
            name: "Pancuchy stehenné Venosan 6002",
            detail: "S-XL, kompres. trieda 2",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 16.14,
            covered: 16.14,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G93117",
            name: "Pančuchy zdravotné kompresívne stehenné",
            detail: "Kompresná trieda II. liečba varixov",
            manufacturer: "MOL",
            country: "IT",
            unit: "pár",
            price: 16.14,
            covered: 16.14,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G83681",
            name: "PROMAX Standard, stehenné panč.nekĺz. úprava",
            detail: null,
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 16.14,
            covered: 16.14,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G37410",
            name: "Segreta plus stocking",
            detail: "II. K.tr.",
            manufacturer: "IBC",
            country: "IT",
            unit: "pár",
            price: 16.14,
            covered: 16.14,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G29734",
            name: "Lonaris Extra Fejne",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 16.33,
            covered: 16.15,
            copay: 0.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G68000",
            name: "LONARIS COTTON",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 17.61,
            covered: 16.15,
            copay: 1.46,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G59878",
            name: "MAXIS MICRO",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 18.22,
            covered: 16.15,
            copay: 2.07,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G79787",
            name: "AVICENUM 360",
            detail: "II. K.tr.",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 18.33,
            covered: 16.15,
            copay: 2.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G58737",
            name: "Pančuchy Lonaris Exclusive",
            detail: "stehenné,farebné,nekĺzavá úprava,kompresná trieda 2",
            manufacturer: "LNN",
            country: "CZ",
            unit: "pár",
            price: 18.33,
            covered: 16.15,
            copay: 2.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G58739",
            name: "Pančuchy Lonaris Extra Feine Soft",
            detail: "stehenné,farebné,nekĺzavá úprava,kompresná trieda 2",
            manufacturer: "LNN",
            country: "CZ",
            unit: "pár",
            price: 18.33,
            covered: 16.15,
            copay: 2.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G58738",
            name: "Pančuchy Lonaris Micro Soft",
            detail: "stehenné,farebné,nekĺzavá úprava,kompresná trieda 2",
            manufacturer: "LNN",
            country: "CZ",
            unit: "pár",
            price: 18.33,
            covered: 16.15,
            copay: 2.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G86385",
            name: "ELAST 0402 LUX - Pančuchy kompresívne stehenné",
            detail: "II. K.tr. nekĺzavá úprava",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 18.84,
            covered: 16.15,
            copay: 2.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G86386",
            name: "ELAST 0403 LUX - Pančuchy kompresívne stehenné",
            detail: "II. K.tr. bez špice,nekĺzavá úprava",
            manufacturer: "TNE",
            country: "LV",
            unit: "pár",
            price: 18.84,
            covered: 16.15,
            copay: 2.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G88887",
            name: "Zdravotné sťahujúce pančuchy 2 trieda  kompresie PT 0403",
            detail: "KT.2, liečba varixov",
            manufacturer: "PTM",
            country: "PL",
            unit: "pár",
            price: 18.9,
            covered: 16.15,
            copay: 2.75,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G36824",
            name: "Lonaris",
            detail: "II. K.tr., s čipkou",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 18.94,
            covered: 16.15,
            copay: 2.79,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G68001",
            name: "LONARIS COTTON",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 18.94,
            covered: 16.15,
            copay: 2.79,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G36823",
            name: "Lonaris Extra",
            detail: "II. K.tr., nekĺzavá úprava",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 18.94,
            covered: 16.15,
            copay: 2.79,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G52805",
            name: "Pančuchy stehenné MAXIS-COMFORT COTTON",
            detail: "II. K.tr., nekĺzavá úprava",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 18.94,
            covered: 16.15,
            copay: 2.79,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G2846A",
            name: "Pančucha kompresívna stehenná JOBST OPAQUE CCL2",
            detail: "2. kompresná trieda (KT II.), rôzne farby, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "pár",
            price: 19.76,
            covered: 16.15,
            copay: 3.61,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G83624",
            name: "AVICENUM 360 COTTON",
            detail: "stehenné pančuchy s prímesou bavlny a mikrokapsulami Skintex",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 20.82,
            covered: 16.15,
            copay: 4.67,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G83625",
            name: "AVICENUM 360 COTTON",
            detail: "stehenné pančuchy s prímesou bavlny a úpravou Sanitized Silver",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 20.82,
            covered: 16.15,
            copay: 4.67,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G79788",
            name: "AVICENUM 360",
            detail: "II. K.tr.",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 21.26,
            covered: 16.15,
            copay: 5.11,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G74401",
            name: "MAXIS BRILLANT",
            detail: "II. K. tr., s nekĺzavou úpravou",
            manufacturer: "MAX",
            country: "CZ",
            unit: "pár",
            price: 21.55,
            covered: 16.15,
            copay: 5.4,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G88146",
            name: "VENOFLEX KOKOON AG",
            detail: "elastické stehenné pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 21.55,
            covered: 16.15,
            copay: 5.4,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: "s krajkou!, telová/čierna, otvorená/uzavretá, ľahšie sa navliekajú",
          },
          {
            code: "G96301",
            name: "Avicenum 360 FINE stehenné pančuchy",
            detail: "KRAJKA/LEM, s/bez špice",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 23.05,
            covered: 16.15,
            copay: 6.9,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G72322",
            name: "VENO MICRO AG",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 23.69,
            covered: 16.15,
            copay: 7.54,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G2843A",
            name: "Pančucha kompresívna stehenná JOBST Ultra Sheer CCL2",
            detail: "2. kompresná trieda (KT II.), rôzne farby, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "pár",
            price: 24.43,
            covered: 16.15,
            copay: 8.28,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G98244",
            name: "Pančuchy stehenné Venoflex Micro® AG",
            detail: "elastické s nekĺzavým ukončením, kompresívna trieda II.",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 25.58,
            covered: 16.15,
            copay: 9.43,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: "čipka/lem, telová/čierna, otv/uzavr., ťažšie sa navliekajú, sú tuhšie, lepšie pri veľkých opuchoch",
          },
          {
            code: "G72321",
            name: "VENO ELEGANCE AG",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 26.96,
            covered: 16.15,
            copay: 10.81,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G59879",
            name: "MAXIS-MICRO",
            detail: "II. K.tr., nekĺzavá úprava",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 27.33,
            covered: 16.15,
            copay: 11.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G88147",
            name: "VENOFLEX CITY CONFORT COTON AG",
            detail: "elastické stehenné pančuchy, II. kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 32.96,
            covered: 16.15,
            copay: 16.81,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: "iba lem, iba čierna, otv/uzavr., 42% podiel bavlny - menej dráždivé na pokožku), oficiálne sú pánske - majú dlhšie chodidlo",
          },
          {
            code: "G79888",
            name: "MEDIVEN ELEGANCE",
            detail: "II. K.tr., s nekĺzavou úpravou",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 36.01,
            covered: 16.15,
            copay: 19.86,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G79885",
            name: "MEDIVEN PLUS",
            detail: "II. K.tr., s nekĺzavou úpravou",
            manufacturer: "MDB",
            country: "DE",
            unit: "pár",
            price: 36.01,
            covered: 16.15,
            copay: 19.86,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G81899",
            name: "Pančuchy stehenné Venosan 5002",
            detail: "klasický patent, S-XL, kompres. trieda 2",
            manufacturer: "SAZ",
            country: "CH",
            unit: "pár",
            price: 49.63,
            covered: 16.15,
            copay: 33.48,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G35091",
            name: "Sigvaris Plus",
            detail: "II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 50.87,
            covered: 16.15,
            copay: 34.72,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G3.1.2",
        title: "KOMPRESNÁ TRIEDA II.stupeň",
        limit: 18.13,
        items: [
          {
            code: "G99346",
            name: "Pančuchy stehenné Avicenum Hospital 2",
            detail: "kompresívna trieda II, S-XXL",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 10.96,
            covered: 10.96,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G98464",
            name: "Pančuchy kompresné stehenné špeciálne AR 1007",
            detail: "kompresná trieda 2, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "pár",
            price: 17.19,
            covered: 17.19,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G6066A",
            name: "Pančuchy stehenné proti embólii",
            detail: "kompresná trieda II.",
            manufacturer: "MZX",
            country: "TR",
            unit: "ks",
            price: 18.08,
            covered: 18.08,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G93115",
            name: "Pančuchy stehenné",
            detail: "Kompresná trieda II. liečba varixov, špeciálna",
            manufacturer: "MOL",
            country: "IT",
            unit: "pár",
            price: 18.13,
            covered: 18.13,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G94282",
            name: "Pančuchy stehenné VENOFLEX® Clinic",
            detail: "elastické špeciálne, rôzne veľkosti, kompr.trieda II",
            manufacturer: "TLP",
            country: "FR",
            unit: "pár",
            price: 18.13,
            covered: 18.13,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
          {
            code: "G83881",
            name: "Pančucha stehenná  PT 0404",
            detail: "II. K.tr.špeciálna",
            manufacturer: "PTM",
            country: "PL",
            unit: "pár",
            price: 18.65,
            covered: 18.13,
            copay: 0.52,
            prescription: ["ANG", "CCH", "CHI", "INT", "ORT", "UCH"],
            note: null,
          },
        ],
      },
      {
        id: "G3.2",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 18.24,
        items: [
          {
            code: "G30922",
            name: "Lonaris Extra",
            detail: "III. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "pár",
            price: 18.23,
            covered: 18.23,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G93684",
            name: "AVICENUM 520",
            detail: "III.K.tr.pančuchy kompresívne stehenné s/bez špičky",
            manufacturer: "ARA",
            country: "CZ",
            unit: "pár",
            price: 21.31,
            covered: 18.24,
            copay: 3.07,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G27224",
            name: "MAXIS-MICRO",
            detail: "III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "pár",
            price: 21.31,
            covered: 18.24,
            copay: 3.07,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
          {
            code: "G35099",
            name: "Sigvaris Plus",
            detail: "III. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 51.33,
            covered: 18.24,
            copay: 33.09,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G3.3",
        title: "KOMPRESNÁ TRIEDA IV. stupeň",
        limit: 49.71,
        items: [
          {
            code: "G35102",
            name: "Sigvaris Plus",
            detail: "IV. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "pár",
            price: 49.71,
            covered: 49.71,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G4",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHY STEHENNÉ S UCHYTENÍM V PÁSE",
    subgroups: [
      {
        id: "G4.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň",
        limit: 10.04,
        items: [
          {
            code: "G77664",
            name: "LONARIS Micro, stehenná pančucha",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 9,
            covered: 9,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G29735",
            name: "Lonaris Extra",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 10.03,
            covered: 10.03,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G93682",
            name: "AVICENUM 360",
            detail: "II.K.tr.pančucha kompresívna stehenná s/bez špičky, s upínaním v páse",
            manufacturer: "ARA",
            country: "CZ",
            unit: "ks",
            price: 11.57,
            covered: 10.04,
            copay: 1.53,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G59880",
            name: "MAXIS MICRO",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 11.87,
            covered: 10.04,
            copay: 1.83,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G72323",
            name: "VENO ELEGANCE AG/HT",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 21.95,
            covered: 10.04,
            copay: 11.91,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G35105",
            name: "SIGVARIS - stehenná pančucha",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 25.97,
            covered: 10.04,
            copay: 15.93,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G4.2",
        title: "KOMPRESNÁ TRIEDA III. stupeň",
        limit: 11,
        items: [
          {
            code: "G27225",
            name: "MAXIS-MICRO",
            detail: "III. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "ks",
            price: 12.78,
            covered: 11,
            copay: 1.78,
            prescription: ["ANG", "CCH", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G5",
    title: "KOMPRESÍVNE ELASTICKÉ PANČUCHOVÉ NOHAVICE",
    subgroups: [
      {
        id: "G5.1",
        title: "KOMPRESNÁ TRIEDA II. stupeň, dámske",
        limit: 30.81,
        items: [
          {
            code: "G98465",
            name: "Nohavice pančuchové kompresné dámske AR 0008",
            detail: "kompresná trieda 2, 140 den, rôzne veľkosti a farby",
            manufacturer: "CZN",
            country: "IT",
            unit: "ks",
            price: 30.06,
            covered: 30.06,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G98466",
            name: "Nohavice pančuchové kompresívne špeciálne AR1009",
            detail: "kompresná trieda 2,140 den, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "ks",
            price: 30.54,
            covered: 30.54,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G5143A",
            name: "Nohavice pančuchové Avicenum PHLEBO 360 FINE",
            detail: "otvorená špica / zatvorená špica, veľkosti S normal - XXL long",
            manufacturer: "ARA",
            country: "CZ",
            unit: "ks",
            price: 30.74,
            covered: 30.74,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G6064A",
            name: "Nohavice pančuchové kompresívne",
            detail: "kompresná trieda II.",
            manufacturer: "MZX",
            country: "TR",
            unit: "ks",
            price: 30.74,
            covered: 30.74,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G98467",
            name: "Nohavice pančuchové kompresné dámske AR 0010",
            detail: "kompresná trieda 2, so zatvorenou špicou, rôzne veľkosti a farby",
            manufacturer: "CEZ",
            country: "IT",
            unit: "ks",
            price: 30.79,
            covered: 30.79,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G98245",
            name: "Pančuchové nohavice Venoflex Micro® AT",
            detail: "elastické, kompresívna trieda II., rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 30.79,
            covered: 30.79,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G77665",
            name: "LONARIS Micro",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 30.81,
            covered: 30.81,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G81902",
            name: "Nohavice pančuchové Venosan 6002",
            detail: "S-XL, kompres. trieda 2",
            manufacturer: "SAZ",
            country: "CH",
            unit: "ks",
            price: 30.81,
            covered: 30.81,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G93114",
            name: "Nohavice pančuchové zdravotné",
            detail: "Kompresná trieda II. liečba varixov S, M, L, XL, XXL",
            manufacturer: "MOL",
            country: "IT",
            unit: "ks",
            price: 30.81,
            covered: 30.81,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G92211",
            name: "Venoflex Kokoon AT",
            detail: "elastické pančuchové nohavice, II.kompresívna trieda",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 30.81,
            covered: 30.81,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G86506",
            name: "Avicenum 360",
            detail: "Nohavice pančuchové dámske II.KT",
            manufacturer: "ARS",
            country: "CZ",
            unit: "ks",
            price: 31.61,
            covered: 30.81,
            copay: 0.8,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G83880",
            name: "Zdravotné sťahujúce pančuchové nohavice 2 trieda kompresie PT 0401",
            detail: "KT.2, liečba varixov",
            manufacturer: "PTM",
            country: "PL",
            unit: "ks",
            price: 31.75,
            covered: 30.81,
            copay: 0.94,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G59881",
            name: "MAXIS-MICRO",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "SK",
            unit: "ks",
            price: 33.62,
            covered: 30.81,
            copay: 2.81,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G86387",
            name: "ELAST 0404 LUX - Nohavice pančuchové kompresívne",
            detail: "II. K.tr.",
            manufacturer: "TNE",
            country: "LV",
            unit: "ks",
            price: 34.5,
            covered: 30.81,
            copay: 3.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G36817",
            name: "Lonaris Extra",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 34.5,
            covered: 30.81,
            copay: 3.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G37409",
            name: "Segreta plus panthyhose",
            detail: "II. K.tr.",
            manufacturer: "IBC",
            country: "IT",
            unit: "ks",
            price: 34.5,
            covered: 30.81,
            copay: 3.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G72327",
            name: "VENO MICRO AT",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 34.5,
            covered: 30.81,
            copay: 3.69,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G2847A",
            name: "Pančuchové nohavice kompresívne JOBST OPAQUE CCL2",
            detail: "2. kompresná trieda (KT II.), rôzne farby, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 34.62,
            covered: 30.81,
            copay: 3.81,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G74402",
            name: "MAXIS BRILLANT",
            detail: "II. K. tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 36.99,
            covered: 30.81,
            copay: 6.18,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G2844A",
            name: "Pančuchové nohavice kompresívne JOBST Ultra Sheer CCL2",
            detail: "2. kompresná trieda (KT II.), rôzne farby, veľ. I. - VI.",
            manufacturer: "BNJ",
            country: "DE",
            unit: "ks",
            price: 37.01,
            covered: 30.81,
            copay: 6.2,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G79886",
            name: "MEDIVEN PLUS",
            detail: "II. K.tr., dámske",
            manufacturer: "MDB",
            country: "DE",
            unit: "ks",
            price: 38.62,
            covered: 30.81,
            copay: 7.81,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G79889",
            name: "MEDIVEN ELEGANCE",
            detail: "II. K.tr., dámske",
            manufacturer: "MDB",
            country: "DE",
            unit: "ks",
            price: 39.53,
            covered: 30.81,
            copay: 8.72,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G72325",
            name: "VENO ELEGANCE AT",
            detail: null,
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 41.91,
            covered: 30.81,
            copay: 11.1,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G35092",
            name: "Sigvaris Plus",
            detail: "II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "ks",
            price: 53.94,
            covered: 30.81,
            copay: 23.13,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G5.2",
        title: "KOMPRESNÁ TRIEDA II. stupeň, tehotenské",
        limit: 45.65,
        items: [
          {
            code: "G6065A",
            name: "Nohavice pančuchové tehotenské",
            detail: "kompresná trieda II.",
            manufacturer: "MZX",
            country: "TR",
            unit: "ks",
            price: 42.95,
            covered: 42.95,
            copay: 0,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
          {
            code: "G59882",
            name: "Maxis-Micro",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 42.98,
            covered: 42.98,
            copay: 0,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
          {
            code: "G77667",
            name: "LONARIS Micro",
            detail: "II. K. tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 45.65,
            covered: 45.65,
            copay: 0,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
          {
            code: "G36819",
            name: "Lonaris  Extra",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 51,
            covered: 45.65,
            copay: 5.35,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
          {
            code: "G72328",
            name: "VENO ELEGANCE AT/U",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 51,
            covered: 45.65,
            copay: 5.35,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
          {
            code: "G74403",
            name: "MAXIS BRILLANT",
            detail: "II. K. tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 51.03,
            covered: 45.65,
            copay: 5.38,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
          {
            code: "G79890",
            name: "MEDIVEN ELEGANCE",
            detail: "II. K. tr.",
            manufacturer: "MDB",
            country: "DE",
            unit: "ks",
            price: 51.03,
            covered: 45.65,
            copay: 5.38,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
          {
            code: "G35093",
            name: "Sigvaris Plus",
            detail: "II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "ks",
            price: 61.97,
            covered: 45.65,
            copay: 16.32,
            prescription: ["ANG", "CCH", "GYN", "INT"],
            note: null,
          },
        ],
      },
      {
        id: "G5.3",
        title: "KOMPRESNÁ TRIEDA II. stupeň, pánske",
        limit: 48.66,
        items: [
          {
            code: "G59883",
            name: "Maxis-Micro",
            detail: "II. K.tr.",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 42.98,
            covered: 42.98,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G77666",
            name: "LONARIS Micro",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 48.66,
            covered: 48.66,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G36818",
            name: "Lonaris Extra",
            detail: "II. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 54.39,
            covered: 48.66,
            copay: 5.73,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
          {
            code: "G72330",
            name: "VENO ELEGANCE AT/H",
            detail: "II. K.tr.",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 54.39,
            covered: 48.66,
            copay: 5.73,
            prescription: ["ANG", "CCH", "DER", "CHI", "INT"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G6",
    title: "KOMPRESÍVNY RAMENNÝ NÁVLEK A KOMPRESÍVNA RUKAVICA",
    subgroups: [
      {
        id: "G6.1",
        title: "KOMPRESÍVNY RAMENNÝ NÁVLEK A KOMPRESÍVNA RUKAVICA, KOMPRESNÁ TRIEDA II. stupeň",
        limit: 22.81,
        items: [
          {
            code: "G88361",
            name: "Návlek ramenný Avicenum 360",
            detail: "CG/CH, KT II",
            manufacturer: "ARS",
            country: "CZ",
            unit: "ks",
            price: 8.92,
            covered: 8.92,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G86403",
            name: "TONUS 0403 - Návlek kompresívny ramenný",
            detail: "II. K.tr.",
            manufacturer: "TNE",
            country: "LV",
            unit: "ks",
            price: 9.06,
            covered: 9.06,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G88363",
            name: "Návlek ramenný Avicenum 360",
            detail: "s rukavicou v jednom kuse, KT II,",
            manufacturer: "ARS",
            country: "CZ",
            unit: "ks",
            price: 9.83,
            covered: 9.83,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G88362",
            name: "Návlek ramenný s rukavicou Avicenum 360",
            detail: "AG/AH, KT II",
            manufacturer: "ARS",
            country: "CZ",
            unit: "ks",
            price: 11.69,
            covered: 11.69,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G70880",
            name: "Návlek pažný s rukavicou DEONA",
            detail: "Klasik Garde, upínanie krajka/lem/na hruď, kompres. tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "ks",
            price: 16.32,
            covered: 16.32,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G85106",
            name: "Maxis SOFT",
            detail: "ramenný návlek, CG/CH",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 22.81,
            covered: 22.81,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G85104",
            name: "Maxis SOFT",
            detail: "ramenný návlek s rukavicou, AG/AH",
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 24.04,
            covered: 22.81,
            copay: 1.23,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G72332",
            name: "VENO ELEGANCE AG/AH",
            detail: null,
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 24.08,
            covered: 22.81,
            copay: 1.27,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G35094",
            name: "Sigvaris",
            detail: "Ramenný návlek, II. K.tr.",
            manufacturer: "GAN",
            country: "CH",
            unit: "ks",
            price: 36.52,
            covered: 22.81,
            copay: 13.71,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G6.2",
        title: "KOMPRESÍVNA RUKAVICA, KOMPRESNÁ TRIEDA II. stupeň",
        limit: 11.71,
        items: [
          {
            code: "G87633",
            name: "MAXIS SOFT, rukavica kompresívna bez prstov,II.KT",
            detail: null,
            manufacturer: "MAX",
            country: "CZ",
            unit: "ks",
            price: 11.71,
            covered: 11.71,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G72333",
            name: "Thuasne",
            detail: null,
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 11.71,
            covered: 11.71,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G6.3",
        title: "KOMPRESÍVNY RAMENNÝ NÁVLEK A KOMPRESÍVNA RUKAVICA, KOMPRESNÁ TRIEDA III. stupeň",
        limit: 6.77,
        items: [
          {
            code: "G29738",
            name: "Lonaris Extra",
            detail: "Ramenný návlek,  III. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 6.77,
            covered: 6.77,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G29741",
            name: "Lonaris Extra",
            detail: "Ramenný návlek a rukavica, III. K.tr.",
            manufacturer: "LOA",
            country: "CZ",
            unit: "ks",
            price: 9.08,
            covered: 6.77,
            copay: 2.31,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
        ],
      },
    ],
  },
  {
    id: "G8",
    title: "INÉ POMÔCKY PRE KOMPRESÍVNU LIEČBU",
    subgroups: [
      {
        id: "G8.1",
        title: "PRÍSTROJ NA KOMPRESÍVNU LIEČBU",
        limit: 810.1,
        items: [
          {
            code: "G95393",
            name: "Systém terapeutický kompresný pneumatický PCD 51",
            detail: "721A",
            manufacturer: "MGF",
            country: "IL",
            unit: "ks",
            price: 883.55,
            covered: 810.1,
            copay: 73.45,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
          {
            code: "G88139",
            name: "prístroj na liečbu presoterapiou Pneuven MEDI 6.7",
            detail: "sekvenčná kompresívna drenáž",
            manufacturer: "EKO",
            country: "CZ",
            unit: "ks",
            price: 983.95,
            covered: 810.1,
            copay: 173.85,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
        ],
      },
      {
        id: "G8.2.1",
        title: "PRÍSLUŠENSTVO K PRÍSTROJU NA KOMPRESÍVNU LIEČBU, horná končatina",
        limit: 101.48,
        items: [
          {
            code: "G41618",
            name: "Návlek na ruku 7-komorový",
            detail: "Príslušenstvo k prístrojom  Pneuven Bevuk / MEDI",
            manufacturer: "EKO",
            country: "CZ",
            unit: "ks",
            price: 78.7,
            covered: 78.7,
            copay: 0,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
          {
            code: "G98231",
            name: "Návlek na ruku a rameno 8-komorový",
            detail: "príslušenstvo k terapeutickému kompresnému systému PCD 51",
            manufacturer: "MGF",
            country: "IL",
            unit: "ks",
            price: 110.6,
            covered: 101.48,
            copay: 9.12,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
          {
            code: "G41617",
            name: "Návlek na ruku s ramenom",
            detail: "Príslušenstvo k prístrojom Pneuven Bevuk/MEDI",
            manufacturer: "EKO",
            country: "CZ",
            unit: "ks",
            price: 110.7,
            covered: 101.48,
            copay: 9.22,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
        ],
      },
      {
        id: "G8.2.2",
        title: "PRÍSLUŠENSTVO K PRÍSTROJU NA KOMPRESÍVNU LIEČBU, dolná končatina",
        limit: 252.33,
        items: [
          {
            code: "G41623",
            name: "Návlek na nohu 7-komorový",
            detail: "Príslušenstvo k prístrojom Pneuven Bevuk / MEDI",
            manufacturer: "EKO",
            country: "CZ",
            unit: "ks",
            price: 117.5,
            covered: 117.5,
            copay: 0,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
          {
            code: "G88143",
            name: "Návlek nohavice",
            detail: "Príslušenstvo k prístrojom Pneuven Bvuk/MEDI",
            manufacturer: "EKO",
            country: "CZ",
            unit: "ks",
            price: 324.72,
            covered: 252.33,
            copay: 72.39,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
          {
            code: "G98230",
            name: "Návlek nohavicový 16-komorový",
            detail: "príslušenstvo k terapeutickému kompresnému systému PCD 51",
            manufacturer: "MGF",
            country: "IL",
            unit: "ks",
            price: 563.76,
            covered: 252.33,
            copay: 311.43,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
          {
            code: "G95396",
            name: "Návlek na nohu 8-komorový",
            detail: "príslušenstvo k terapeutickému kompresnému systému PCD 51",
            manufacturer: "MGF",
            country: "IL",
            unit: "ks",
            price: 137.59,
            covered: 27.76,
            copay: 109.83,
            prescription: ["ANG", "RHB", "ZP"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.1",
        title: "Podložka pod kompresívny obväz",
        limit: 15.31,
        items: [
          {
            code: "G79882",
            name: "MOBIDERM",
            detail: "33 cm x 1m",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 15.31,
            covered: 15.31,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G79883",
            name: "MOBIDERM",
            detail: "10 cm x 3 m",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 14.93,
            covered: 14.93,
            copay: 0,
            prescription: ["ANG", "CCH", "DER", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.2",
        title: "Návlek ramenný na liečbu lymfedému",
        limit: 40.64,
        items: [
          {
            code: "G94283",
            name: "Návlek ramenný Mobiderm® Standard",
            detail: "mobilizačný odev na liečbu lymfedému, rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 40.64,
            covered: 40.64,
            copay: 0,
            prescription: ["ANG", "CCH", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.3",
        title: "Rukavica na liečbu lymfedému bez prstov",
        limit: 25.17,
        items: [
          {
            code: "G94284",
            name: "Rukavička bez prstov Mobiderm®",
            detail: "mobilizačný odev na liečbu lymfedému, obojstranná, rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 25.17,
            covered: 25.17,
            copay: 0,
            prescription: ["ANG", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.4",
        title: "Rukavica na liečbu lymfedému s prstami",
        limit: 52.14,
        items: [
          {
            code: "G94285",
            name: "Rukavička s prstami Mobiderm®",
            detail: "mobilizačný odev na liečbu lymfedému, ľavá / pravá, rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 52.14,
            covered: 52.14,
            copay: 0,
            prescription: ["ANG", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.5",
        title: "Návlek na hornú končatinu s nastaviteľnou kompresiou",
        limit: 100.18,
        items: [
          {
            code: "G96299",
            name: "Ramenný návlek s rukavičkou a palcom Mobiderm® Autofit",
            detail: "mobilizačný odev na liečbu lymfedému s individuálnym nastavením, rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 100.18,
            covered: 100.18,
            copay: 0,
            prescription: ["ANG", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.6",
        title: "Mobilizačný stehenný návlek s chodidlom na liečbu lymfedému",
        limit: 157.1,
        items: [
          {
            code: "G92251",
            name: "Bandáž kompresívna DEONA",
            detail: "Spec, T-B, T-C, lymf. Opuchy DKK, kompres. Tr. 2",
            manufacturer: "DEO",
            country: "CZ",
            unit: "ks",
            price: 64.26,
            covered: 64.26,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G98237",
            name: "Stehenný návlek Mobiderm® Autofit",
            detail: "mobilizačný stehenný návlek s chodidlom na liečbu lymfedému s individuálnym nastavením kompresie, rôzne veľkosti",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 157.1,
            covered: 157.1,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.7",
        title: "Mobilizačné šortky na liečbu lymfedému v oblasti panvy a genitálií",
        limit: 127.08,
        items: [
          {
            code: "G7631A",
            name: "Šortky kompresívne dámske Mobiderm Intimate Short",
            detail: "mobilizačné šortky na liečbu lymfedému s mobilizačnou vložkou",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 123.25,
            covered: 123.25,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
          {
            code: "G7632A",
            name: "Šortky kompresívne pánske Mobiderm Intimate Short",
            detail: "mobilizačné šortky na liečbu lymfedému s mobilizačnou vložkou",
            manufacturer: "TLP",
            country: "FR",
            unit: "ks",
            price: 127.08,
            covered: 127.08,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
        ],
      },
      {
        id: "G8.3.8",
        title: "Mobilizačná podprsenka na liečbu lymfedému",
        limit: 119.85,
        items: [
          {
            code: "G7633A",
            name: "Podprsenka kompresívna mobilizačná Mobiderm Intimate-Bra",
            detail: "na liečbu lymfedému s mobilizačnými vložkami, rôzne veľkosti",
            manufacturer: "THU",
            country: "DE",
            unit: "ks",
            price: 119.85,
            covered: 119.85,
            copay: 0,
            prescription: ["ANG", "CCH", "CHI", "INT", "ONK", "RHB"],
            note: null,
          },
        ],
      },
    ],
  },
];
